project:
  type: website
  output-dir: "."

website:
  title: "Jackson Boyer"
  navbar:
    pinned: true
    background: info
    # primar, secondary, light, success, danger, warning, info

    left:
      - text: Project
        href: project.qmd
      - text: Blog
        href: blog-listing.qmd
      - text: Classwork
        href: danl-200-cw-10.qmd # Quarto file for the classwork 10

  page-footer: 
    center: "Powered with GitHub and Quarto<br>Â© Jackson Boyer, 2023"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
